### ISSUE TITLE
Just a observation

### ISSUE THREAD

**Issue by qnoox** [jeffnappi/action-cable-chat#3]
Hello Jeff!

Just to let you know

This part does not work on heroku:

> Generate Job to handle Broadcasts
> 
> rails g job BroadcastMessage
> Add after_create_commit hook to send broadcast job.
> 
> after_create_commit { BroadcastMessageJob.perform_later self }

**Comment by jeffnappi** [comment]
Hey there, thanks for the feedback - this project was put together when Rails 5 was still in Release Candidate. When I have a moment, I plan to update it and include instructions for launching on various PaaS.

**Comment by qnoox** [comment]
Just to share the error log: (note it's a strange issue it works on local but not on heroku production)
2017-02-06T23:31:00.132235+00:00 app[web.1]: [ActionCable] [test@mail.com] Could not execute command from {"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\"}", "data"=>"\"message: message\""}) [NoMethodError - undefined method `except' for "message: message":String
2017-02-06T23:31:00.132249+00:00 app[web.1]: Did you mean?  exec]: /app/vendor/bundle/ruby/2.3.0/gems/actioncable-5.0.1/lib/action_cable/channel/base.rb:272:in `block in action_signature' | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-5.0.1/lib/action_cable/channel/base.rb:271:in `tap' | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-5.0.1/lib/action_cable/channel/base.rb:271:in `action_signature' | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-5.0.1/lib/action_cable/channel/base.rb:169:in `perform_action' | /app/vendor/bundle/ruby/2.3.0/gems/actioncable-5.0.1/lib/action_cable/connection/subscriptions.rb:53:in `perform_action'

**Comment by jeffnappi** [comment]
I would gladly accept a pull request if you are able to resolve this :)
